### ISSUE TITLE
Border radius argument doesn't agree with folder structure

### ISSUE THREAD

**Issue by danikron** [TiZ-EX1/xfwm4-minibox-theme#1]
While the border radius argument only accepts input of the form '#px', the generate.sh script calls for folders titled '${SIZE}px', which gives an error since the folders '#pxpx' don't exist.

**Comment by TiZ-HugLife** [comment]
Actually, the border radius argument should only take a single number, not #px. And the size argument takes a single number too. Hmm... actually, it looks like my last commit to try and get rid of the contradiction actually just worsened the contradiction. I think I wanted it to be possible for there to be more styles in the future as opposed to just border sizes, but then ultimately decided it wasn't worth. I'll fix the readme, sorry.

**Comment by TiZ-HugLife** [comment]
There was a problem in the generate script itself, too. It may not be something you agree with, but at least it's consistent now. Please close if you're satisfied with the fix.

**Comment by danikron** [comment]
Yeah, now it works just as expected. Thanks kindly.
